# Generated by Django 3.0.4 on 2020-03-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20200323_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answer',
            field=models.BooleanField(default=False, verbose_name='Ответы'),
        ),
    ]
