# Generated by Django 3.0.4 on 2020-03-23 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecrutRegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Ваше имя:')),
                ('planet', models.CharField(max_length=50, verbose_name='Ваша планета обитания:')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)], verbose_name='Ваш возраст:')),
                ('mail', models.EmailField(max_length=254, verbose_name='Ваша почта:')),
            ],
        ),
    ]
