# Generated by Django 3.0.4 on 2020-03-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20200324_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recrutregistrationform',
            options={'verbose_name': 'Зарегистрированный рекрут', 'verbose_name_plural': 'Зарегистрированные рекруты'},
        ),
    ]
