# Generated by Django 3.0.4 on 2020-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20200324_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recrut_answers', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=9)),
            ],
        ),
    ]
