# Generated by Django 3.0.4 on 2020-04-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
